package com.volfine.model;

import com.volfine.model.base.BaseEmailAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmailAccount extends BaseEmailAccount<EmailAccount> {
	
}
