package com.volfine.model;

import com.volfine.model.base.BaseOrderDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDetail extends BaseOrderDetail<OrderDetail> {
	
}
