package com.volfine.model;

import com.volfine.model.base.BaseQuotedPrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuotedPrice extends BaseQuotedPrice<QuotedPrice> {
	
}
