package com.volfine.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public M setClassify(java.lang.String classify) {
		set("classify", classify);
		return (M)this;
	}
	
	public java.lang.String getClassify() {
		return getStr("classify");
	}

	public M setBasePrice(java.math.BigDecimal basePrice) {
		set("base_price", basePrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getBasePrice() {
		return get("base_price");
	}

	public M setSalePrice(java.math.BigDecimal salePrice) {
		set("sale_price", salePrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getSalePrice() {
		return get("sale_price");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setWarranty(java.lang.String warranty) {
		set("warranty", warranty);
		return (M)this;
	}
	
	public java.lang.String getWarranty() {
		return getStr("warranty");
	}

	public M setWeight(java.lang.Float weight) {
		set("weight", weight);
		return (M)this;
	}
	
	public java.lang.Float getWeight() {
		return getFloat("weight");
	}

}
