package com.volfine.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderDetail<M extends BaseOrderDetail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	public M setModelNumber(java.lang.String modelNumber) {
		set("model_number", modelNumber);
		return (M)this;
	}
	
	public java.lang.String getModelNumber() {
		return getStr("model_number");
	}

	public M setQty(java.lang.Integer qty) {
		set("qty", qty);
		return (M)this;
	}
	
	public java.lang.Integer getQty() {
		return getInt("qty");
	}

	public M setUnitPrice(java.math.BigDecimal unitPrice) {
		set("unit_price", unitPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getUnitPrice() {
		return get("unit_price");
	}

	public M setCondition(java.lang.String condition) {
		set("condition", condition);
		return (M)this;
	}
	
	public java.lang.String getCondition() {
		return getStr("condition");
	}

	public M setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
		return (M)this;
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

}
