package com.volfine.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuotedPrice<M extends BaseQuotedPrice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setModelNumber(java.lang.String modelNumber) {
		set("model_number", modelNumber);
		return (M)this;
	}
	
	public java.lang.String getModelNumber() {
		return getStr("model_number");
	}

	public M setUnit(java.lang.Integer unit) {
		set("unit", unit);
		return (M)this;
	}
	
	public java.lang.Integer getUnit() {
		return getInt("unit");
	}

	public M setPurchasePrice(java.math.BigDecimal purchasePrice) {
		set("purchase_price", purchasePrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getPurchasePrice() {
		return get("purchase_price");
	}

	public M setCondition(java.lang.String condition) {
		set("condition", condition);
		return (M)this;
	}
	
	public java.lang.String getCondition() {
		return getStr("condition");
	}

	public M setSupplier(java.lang.String supplier) {
		set("supplier", supplier);
		return (M)this;
	}
	
	public java.lang.String getSupplier() {
		return getStr("supplier");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
