package com.volfine.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	public M setCustomerId(java.lang.Long customerId) {
		set("customer_id", customerId);
		return (M)this;
	}
	
	public java.lang.Long getCustomerId() {
		return getLong("customer_id");
	}

	public M setSupplierId(java.lang.Long supplierId) {
		set("supplier_id", supplierId);
		return (M)this;
	}
	
	public java.lang.Long getSupplierId() {
		return getLong("supplier_id");
	}

	public M setShippingCost(java.math.BigDecimal shippingCost) {
		set("shipping_cost", shippingCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getShippingCost() {
		return get("shipping_cost");
	}

	public M setBankCharge(java.math.BigDecimal bankCharge) {
		set("bank_charge", bankCharge);
		return (M)this;
	}
	
	public java.math.BigDecimal getBankCharge() {
		return get("bank_charge");
	}

	public M setTotal(java.math.BigDecimal total) {
		set("total", total);
		return (M)this;
	}
	
	public java.math.BigDecimal getTotal() {
		return get("total");
	}

	public M setPurchaseUnitPrice(java.math.BigDecimal purchaseUnitPrice) {
		set("purchase_unit_price", purchaseUnitPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getPurchaseUnitPrice() {
		return get("purchase_unit_price");
	}

	public M setPurchaseAmount(java.math.BigDecimal purchaseAmount) {
		set("purchase_amount", purchaseAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getPurchaseAmount() {
		return get("purchase_amount");
	}

	public M setExpressFee(java.math.BigDecimal expressFee) {
		set("express_fee", expressFee);
		return (M)this;
	}
	
	public java.math.BigDecimal getExpressFee() {
		return get("express_fee");
	}

	public M setReamrk(java.lang.String reamrk) {
		set("reamrk", reamrk);
		return (M)this;
	}
	
	public java.lang.String getReamrk() {
		return getStr("reamrk");
	}

	public M setPurchaseDate(java.util.Date purchaseDate) {
		set("purchase_date", purchaseDate);
		return (M)this;
	}
	
	public java.util.Date getPurchaseDate() {
		return get("purchase_date");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
